Repository Memo8-KoreaUniv/Kramo, pull requests merged in 2021-06, with the labels that each got.

#17 [API] API 문서 작성
  pages/api/api.yaml
Labels: documentation

#19 [Layout] 카드 반응형 조정 및 모바일 메인 레이아웃
  pages/index.tsx
  pages/main.tsx
  src/components/MainLayout.tsx
  src/components/MenuDrawer.tsx
  src/components/MenuLayout.tsx
  src/components/MenuSider.tsx
  src/utils/size.tsx
Labels: Frontend

#26 [Readme] 리드미 1차 완성
  README.md
Labels: documentation

#29 [Category] 카테고리 메뉴 바 적용
  pages/api/user/[...param].ts
  pages/api/user/index.ts
  pages/login.tsx
  src/components/MainLayout.tsx
  src/components/MenuLayout.tsx
  src/components/MenuSider.tsx
  src/state/categories.ts
  src/state/etc.ts
  src/state/me.ts
  src/types/category.ts
  src/types/user.ts
Labels: Frontend

#30 [Frontend] 메모 로드, 추가, 삭제, pinned 토글 구현
  package-lock.json
  pages/api/api.yaml
  pages/api/user/[...param].ts
  pages/index.tsx
  src/components/main.tsx
  src/model/history.ts
  src/types/index.ts
  src/types/memo.ts
Labels: Backend, Frontend

#16 [날씨] 날씨 관련 모듈 추가 및 테스트 페이지 구성
  package-lock.json
  pages/nowweather.tsx
  src/utils/weather.ts
Labels: Backend, Frontend

#33 [관리자] 관리자 로그인 추가
  pages/admin.tsx
  pages/api/admin/login.ts
  pages/api/admin/users.ts
  pages/api/api.yaml
  src/components/main.tsx
Labels: Backend

#35 [Menu] 메뉴 개선
  pages/mypage.tsx
  src/components/MainLayout.tsx
  src/components/MenuDrawer.tsx
  src/components/MenuLayout.tsx
  src/components/main.tsx
Labels: Frontend

#37 [Frontend] API 로딩 최적화 - 로딩 바(Spinner) 구현 및 getServersideProps 이용
  pages/mypage.tsx
  src/components/Spinner.tsx
  src/interceptors.ts
Labels: Backend, Frontend

#40 [Frontend] 카테고리별 메모 로드
  pages/api/admin/login.ts
  pages/api/admin/users.ts
  pages/api/category/[...param].ts
  pages/api/category/[categoryId].ts
  pages/api/history/[historyId].ts
  pages/api/memo/[...param].ts
  pages/api/memo/[memoId].ts
  pages/api/memo/index.ts
  pages/api/user/[...param].ts
  pages/index.tsx
  pages/mypage.tsx
  src/components/MenuLayout.tsx
  src/components/main.tsx
  src/utils/useMemos.ts
Labels: Frontend

#39 [Frontend] 위치(GPS) 관련 각종 기능 구현
  .prettierrc.js
  README.md
  jest.config.ts
  package-lock.json
  pages/api/place/index.ts
  src/components/MenuLayout.tsx
  src/components/main.tsx
  src/types/index.ts
  src/types/memo.ts
  src/utils/gps.ts
Labels: Backend, Frontend

#45 [Documentation] API 문서 수정 및 보완
  pages/api/api.yaml
Labels: documentation

#46 [Frontend] 메인 화면의 날씨/시간 표시 수정, 메모 추가 시 날씨 입력받도록 수정
  src/components/main.tsx
  src/types/memo.ts
  src/utils/date.ts
  src/utils/gps.ts
  src/utils/useMemos.ts
Labels: Frontend

#48 [Frontend] Header 개편
  pages/mypage.tsx
  src/components/Header.tsx
  src/components/HeaderButton.tsx
  src/components/MainLayout.tsx
  src/components/MenuDrawer.tsx
  src/components/MenuLayout.tsx
  src/components/SubTitle.tsx
  src/components/UserMenu.tsx
  src/components/main.tsx
  src/enum.ts
  src/state/categories.ts
  src/state/category.ts
  src/state/etc.ts
Labels: Frontend

#50 [Frontend] 메모별 drawer 개선
  pages/style.css
  src/components/MenuDrawer.tsx
  src/components/main.tsx
  src/components/memo/MemoCardItem.tsx
  src/components/memo/MemoDetail.tsx
  src/components/memo/MemoTimeline.tsx
  src/components/memo/MemoView.tsx
Labels: Frontend

#51 [Frontend] 위치정보 API 호출 최소화, 로그아웃 시 메모 사라지도록 수정
  pages/api/api.yaml
  src/components/UserMenu.tsx
  src/components/main.tsx
  src/components/memo/MemoCardItem.tsx
  src/components/memo/MemoDetail.tsx
  src/state/memo.ts
  tsconfig.json
Labels: Frontend

#52 [Frontend] 메모 추가기능, 메모 추가 버튼 변경
  pages/api/api.yaml
  pages/editor.tsx
  src/components/AddCardButton.tsx
  src/components/AddMemoButton.tsx
  src/components/MainLayout.tsx
  src/components/memo/MemoView.tsx
  src/state/categories.ts
  src/utils/useMemos.ts
Labels: Frontend

#54 [Frontend] Drawer에서 HTML 표시되도록 수정
  package-lock.json
  package.json
  src/components/memo/MemoCardItem.tsx
Labels: Frontend

#55 [Dummy] 더미 데이터 생성 및 DB 접근, api 테스트 스크립트
  README.md
  package-lock.json
  package.json
  pages/api/api.yaml
  pages/api/memo/[...param].ts
  pages/api/place/index.ts
  pages/api/user/[...param].ts
  pages/api/user/[userId].ts
  pages/api/user/index.ts
  pages/editor.tsx
  pages/hello/world.tsx
  pages/imagetest.tsx
  pages/login.tsx
  pages/style.css
  pages/textmemo.tsx
  public/question.png
  public/question.svg
  src/components/AddCardButton.tsx
  src/components/AddMemoButton.tsx
  src/components/MainLayout.tsx
  src/components/MenuDrawer.tsx
  src/components/MenuLayout.tsx
  src/components/MenuSider.tsx
  src/components/SubTitle.tsx
  src/components/ToastEditor.tsx
  src/components/UserMenu.tsx
  src/components/main.tsx
  src/components/memo/HistoryTimeline.tsx
  src/components/memo/MemoCardItem.tsx
  src/components/memo/MemoDetail.tsx
  src/components/memo/MemoTimeline.tsx
  src/components/memo/MemoView.tsx
  src/components/memo/TimelinePopover.tsx
  src/dummy/dummy.ts
  src/enum.ts
  src/state/categories.ts
  src/state/history.ts
  src/state/me.ts
  src/state/memo.ts
  src/test/category.test.ts
  src/test/dummy.ts
  src/test/dummyCategory.test.ts
  src/test/dummyHistory.test.ts
  src/test/dummyMemo.test.ts
  src/test/history.test.ts
  src/test/memo.test.ts
  src/test/user.test.ts
  src/utils/useMemoPreview.ts
  src/utils/useMemos.ts
  tsconfig.json
Labels: Backend, DB
